### ISSUE TITLE
Feat: Family-friendly Dining Room

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#11]
A _significant_ differentiator for our Montessori-inspired Home is that we don't want to **_restrict_ access** for parents.
If a parent (or grandparent) wants to visit their child (grandchild) for an hour to read with them during the day - provided they inform us beforehand 

Another thing that I haven't seen done in PT schools / day-care providers is allowing parents to have lunch with their children.
I know that as a busy working parent if I was unable to _see_ my child during the day 5 days a week (**`71%` of time!**) I would be quite sad. I _love_ being able to have lunch with our child and think this should be the _norm_ not the exception.
If a parent works in-town and has a **`T1h`** lunch break they should 100% be _encouraged_ to come have lunch with their child **`@home`**. For that we need to have the following setup?

+ [ ] 4 Dining Tables with capacity for 24 people. We already have these in the house they just need to be brought upstairs.
+ [ ] Easily removable + washable table cloths
+ [ ] Clear system for people bringing their own food and cleaning up their mess.
+ [ ] Second microwave oven?

> Longer term we could provide vegan meals for parents [at cost], we've discussed setting this up as a side-biz.

# Todo

+ [ ] Buy more of the "nice" White chairs so we have 12 available.
+ [ ] Clean the _stackable_ IKEA Black chairs (e.g: 8)  and have them stacked in the corner of the room.
+ [ ] Buy or _make_ additional independence-encouraging high chairs. See: https://github.com/bmhco/shared/issues/10
+ [ ] Remove the L-shaped Sofa [this will be controversial with @iteles ... but ultimately a dinning room is not a lounge ...]

**Comment by nelsonic** [comment]
_Definitely_ the materials to set the table should be readily available in the dining room for sure. 👌 
Quite keen to have a movable step in front of the water-dispensing fridge rather than a jug that adults need to re-fill. 
We _have_ a couple of glass water dispensers and they are good on the _surface_, 
but they have 3 key _disadvantages_: 
1. The taps are easy to leave _on_ and just drench the floor, 
  by contrast: the water-dispensing fridge requires constant pressure to dispense. 
2. The dispenser needs to be _manually_ refilled and is too big to fill from the filtered water 
  so it would probably end up being filled from the tap which isn't great quality water.
3. Both the tap and the jug (inside/out) would require regular cleaning to avoid bacteria ..
4. If the water wasn't fully consumed each day it would sit in the container and that's a health hazard/risk.

Happy for someone to change my mind on this with a convincing counterargument, 
But as far as I'm concerned, our water dispenser _is_ the Samsung Fridge https://github.com/dwyl/home/issues/82

**Comment by iteles** [comment]
The only argument I have _for_ the glass water dispenser is that it gets them used to something that is completely accessible to parents and can be replicated in their own homes. A plumbed fridge with a built-in water dispenser, not so much...
This is a pretty big argument as far as I'm concerned but the con of decreased safety of the water (bacteria) just tips it over to the samsung fridge for me.

<hr/>

The only question I have on the family dining area (and I love the concept) @nelsonic is table height:
Are you considering that we will only have adult height tables (in which case we will HAVE to built adult height adapted chairs for all the kids)? 'True' Montessori is kid height (although I don't think this is great for family situations where my firm belief is that everyone should be at the table together, it makes sense for snack time for the kids for example).

In the first instance, we won't be offering lunch and as such, will need some kid-height tables for snack time.
