### ISSUE TITLE
EPIC: Parents & Caregivers Handbook

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#12]
We need create the handbook we all _wish_ already existed for us and other parents/caregivers. 

_initially_ the handbook will be _specific_ to parents who bring their children to our **Montessori Playgroup** #7 
But we will gradually expand it to include generic advice that we will be able to publish as a PDF/EBook for _everyone_.
So if it's _possible_ to make the content suitable to a wider audience, we should put in the extra effort for this.

# Topics

+ [ ] General Health & Safety - including:
  + [ ] First aid protocols
  + [ ] Who to call in emergency (we need the telephone numbers of _both_ parents and one other appointed person)
+ [ ] Insurance coverage - TBD.
+ [ ] Hygiene - washing hands, changing clothes, etc.
+ [ ] Diapers
+ [ ] Toilet independence
+ [ ] Food: Snacks & Meals - cooking; recipes, etc.
  + [ ] Allergies / intolerance!
+ [ ] Appropriate Clothing: indoor clothes, indoor slippers, outdoor shoes / all-weather boots, jackets & waterproof suits
+ [ ] Drop-off & collection times
+ [ ] Communication protocols
+ [ ] Parents / Grandparents / Caregiver attendance
+ [ ] Family Meals, see: #11 
+ [ ] Outings

Add more either by editing this OP or comments. 🙏

**Comment by Stephanymtr** [comment]
I have done a quick research, and these are some of other points we could add:

- [ ] Introduction and welcome: _stress our commitment to the community and excitement about what is to come._ 

- [ ] Child care and teaching philosophies: _Laying out our approach will give parents a good idea of what to expect._

- [ ] Facility hours, care schedules, a calendar, start and end dates, half days, planned special events/outings/excursions and holiday policies. _Parents should know which days they can expect care and which days are “off.”_  We might want to include procedure for sick days and schedule interruptions.

- [ ] Offer some sort of sample daily schedule ? Ex: Walk to the park/outdoor playtime for 1 hour, then 1 hour independent/quiet/focused work, 15 minute of story time, 30 minutes of music/cooking/baking session etc

- [ ] BMH's Phone number(s)?, email(s), website, and physical address.

- [ ] Sign-in and pick-up procedures: _in order to pick up their child, will parent be able to walk in the classroom/playroom after playgroup/focused time ends? What about late and early arrivals/departures. / Should we offer a digital sign in?/_ 
- [ ]  You mentioned appropriate clothing:  We should also ask them to bring extra clothes in case of any "accidents".  
- [ ] Codes of conduct and discipline procedures: Outline how we expect guides to behave toward children and families and children to behave toward guides and other children. 

In the spirit of getting this started, how are we going to make this handbook ?  Will we share a Google Doc file so that all of us can edit or will one of us work on this and have it revised by others ?

**Comment by nelsonic** [comment]
@Stephanymtr as much as I like Google Docs, I'm not a fan of the poor version control / history.
And when it comes to something that we want parents to read, refer to, update and "own", we want version control.
That's why I created a dedicated repo for it: https://github.com/bmhco/handbook
