### ISSUE TITLE
Feat: Shared Calendar

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#16]
# Story 📝 

We need a way of _sharing_ the schedule for the **`PlayGroup` _publicly_** 
so that prospective parents can _easily_ see what the up-coming events are

# Todo ✅ 

+ [ ] Make our _shared_ Google [Gmail] Account Calendar ***`public`*** 
  so that people can see the names of the events but ***NOT*** the a a people` who are invited/confirmed/attending.
+ [ ] Research how to share Google Calendar on a Wordpress Website 
  > **Note**: if this requires a Plug-in it might be the nail in the coffin for our [Wordpress](https://github.com/bmhco/private/issues/118) adventure.

A Sample Events could be: 
+ “Music Making Morning”
+ “Arts & Crafts Creativity” 
+ “Brunch Baking Bonanza”

## Open Question: Should Events be Bilingual or is a `English` OK? ❓ 

In the future when we have a more advanced system we could display the number of available spaces for each day/event so parents know when there are still spaces available.

**Comment by Stephanymtr** [comment]
Hi @nelsonic the shared Google [Gmail] Account Calendar you are referring to is the bragamontessori@gmail.com, right ?

**Comment by Stephanymtr** [comment]
The "Braga Montessori" calendar is now public ✅  

<img width="651" alt="Screenshot 2023-02-22 at 13 58 34" src="https://user-images.githubusercontent.com/91985721/220641702-bdcccaf0-cbd0-4a85-8bb4-73b30d00493d.png">

You said "_so that people can see the names of the events but NOT the a a people` who are invited/confirmed/attending._" I spent a good time looking up how to change that permanently, but it seems that you have to manually unclick the "see guest list" option when creating an event. _Please let me know if there is another way_

![Screenshot 2023-02-22 at 14 01 47](https://user-images.githubusercontent.com/91985721/220644211-70bed849-183f-4c64-a835-0cb3f7d4961e.png)

I looked up how to share Google calendar on a Wordpress website. Surprisingly, it's not hard, and it doesn't need to have a plug in. I created a fake event and followed the steps on here https://wordpress.com/support/google-calendar/. All we need is the embedded link which we can find on the Gmail account under 'Integrate Calendar'.

<img width="1124" alt="Screenshot 2023-02-22 at 14 37 36" src="https://user-images.githubusercontent.com/91985721/220654771-33d37221-dc5f-42ca-a4c7-16ea3a4cff45.png">

This is what it looks like right after adding the calendar block to the website 😥 

<img width="1217" alt="Screenshot 2023-02-22 at 14 32 46" src="https://user-images.githubusercontent.com/91985721/220653163-aeed46d5-5f04-49cb-8aea-8f889266ead7.png">

I already removed the calendar block because I'm hoping to spend the rest of my day researching and creating content for the website. I won't to spend time editing this today. We don't have any events right now, so I think this can wait. Basically, the calendar is super tacky and makes the website look older than it already does. Next step would be to: 

### **Next...**
- [ ] look up if there is away to edit the google calendar. Make it look nice!

**Comment by nelsonic** [comment]
@Stephanymtr yeah, this embed feature is not a priority for Google. They don't care that it's ugly. 
We're going to need to figure out some UI/UX for calendars ... 💭
