### ISSUE TITLE
How to make the absolute BEST homemade bubble solution

### ISSUE THREAD

**Issue by iteles** [bmhco/shared#62]
Blowing bubbles is an absolute dream for kids.

<img width="1078" alt="image" src="https://github.com/bmhco/shared/assets/4185328/fc25ef46-dfc5-4af9-9a73-574cc0e02783">

But once the bubble mixture that you buy from the shop runs out, mixing fairy liquid with water just doesn't really cut it.
This blows (see what I did there? 😇 ) because continuously buying hard, non-recyclable plastic bubble tubes is really pretty awful for the environment ♻️ 

We need to do a little research, find and TEST the top 4 or 5 homemade bubble mixtures.

## Tasks
+ [ ] Research the top 5 (if there are this many) homemade bubble solutions
  + [ ] We need to have at least 1 great one with no weird, hard to find specialty ingredients like corn syrup, so we'll need at least 2 different 'no weird ingredient' recipes to test
+ [ ] Make them!
+ [ ] Test them over the course of a few days with 👦 in similar conditions
+ [ ] Write up our results in a 'We tested the internet's top 5 homemade bubble solutions' type post

**Comment by Stephanymtr** [comment]
_Top 5 results I got from googling_  "Homemade Bubble Solutions":

1. [How to Make Super Bubbles](https://www.homesciencetools.com/article/how-to-make-super-bubbles-science-project/#:~:text=Measure%206%20cups%20of%20water,until%20it%20is%20well%20mixed.)
From: Home Science Tools

Materials:
-**Liquid dish soap**/dishwashing liquid (Joy or blue Dawn brands work best. Try to find one that doesn't say "Ultra"
-**Warm water** (distilled is best for bubble making)
-**Clean container with lid**
-[**Glycerin**](https://www.homesciencetools.com/product/glycerin-30-ml/) or light corn syrup

Instructions:
-Measure 6 cups of water into your container, then pour 1 cup of dish soap into the water. 
-Slowly stir until the soap is mixed in, being careful to not let foam or bubbles form.
-Measure 1 tablespoon of glycerin or 1/4 cup of corn syrup and add it to your container.
-Stir the solution until it is well mixed. For best results, let your solution sit overnight. (Note: if you used "Ultra" dish soap, double the amount of glycerin or corn syrup).
-Dip your bubble wand into the mixture. Wait a few seconds, then BLOW!

------------------------------
2. [How to Make Your Own Bubble Solution](https://www.verywellfamily.com/homemade-bubbles-2764571)
From: Very Well Family.

_This second result/page has multiple recipes:_

**2.1 Homemade Bubble Solution Recipe**
1 cup **water**
2 tablespoons light **Karo syrup** or 2 tablespoons glycerin
4 tablespoons **dishwashing liquid**
Stir together until everything is dissolved.

**2.2 Colored Bubbles** ✔️ 
1 cup **granulated soap** or soap powder
1 quart **warm water**
Liquid **food coloring**
Dissolve soap in warm water. Mix in the food coloring until you get the shade you want.

**2.3 Sugar Bubbles**
Ingredients
1 cup **water**
2 tablespoons **liquid detergent**
1 tablespoon **glycerin**
1 teaspoon **sugar**
Mix all ingredients together until sugar dissolves.

_This recipe claims it will help produce bubbles that are bigger and slower to pop._

------------------------------
3. [How To Make a Homemade Bubbles Mixture](https://www.thesprucecrafts.com/make-your-own-bubble-blowing-mixture-1244214#skip-to-content) ✔️ 
From: The Spruce Crafts

Materials:
-1/2 cup **dish soap**
-1 1/2 cups **water**
-2 teaspoons **sugar**

Instructions:
-Pour 1/2 cup of dish soap into a large cup.
-Add 1 1/2 cups of water to the dish soap in the cup.
-Measure 2 teaspoons of sugar and add it to the water/soap mixture.
-Gently stir your mixture.
-Go outside and have fun blowing bubbles. If you don't use it all, you can pour it into a tightly sealed container.

---------------------------------
4. [How to Make Homemade Bubbles](https://artfulparent.com/how-to-make-homemade-bubbles/) ✔️
From: Artful Parent

Materials:
4 cups warm **water**
1/2 cup **sugar**
1/2 cup blue Dawn **dish soap**
Instructions:
Combine the sugar and water until the sugar dissolves.
Whisk in the soap. Add the dish soap and whisk to combine. Let it sit.

_Note: I know this recipe is similar to the above, but the measurements are very different._ 

---------------------------------

The following result has a similar recipe to another one I shared above, but this one offers substitutes to Glycerin.
 5. [Make Bubbles at Home](https://www.ontariosciencecentre.ca/science-at-home/diy-science-fun/make-bubbles-at-home)
 From: Ontario Science Centre

-3-4 cups of **water**
-1 cup of **dish soap** (the brands Joy or Dawn work best)
-1/3 cup of **glycerin** (substitutions: 1/3 cup of honey or 1/2 cup of corn syrup)

Instructions:
**Glycerin option**: In a bowl, mix 4 cups of water, 1 cup of dish soap and 1/3 cup of glycerin. Pour your mixture into the tray.
**With honey**: Mix 4 cups of water with 1 cup dish soap first, then add 1/3 cup of honey.
**With corn syrup**: Mix 3 cups water, 1 cup soap and 1/2 cup corn syrup.

---------------------------------

6. [Bubble mixture](https://www.bbcgoodfood.com/howto/guide/how-make-bubble-mixture) ✔️ 
From: BBC Good Food.

Makes 350ml
Prep 5 minutes

50ml washing-up liquid (one part)
300ml water (six parts)
-Measure the washing-up liquid into a container.
-Slowly add in the water, being careful not to create too many bubbles at this stage. Gently stir the mixture together to combine – a chopstick is perfect for this.
-If you can, let the bubble mixture rest before using it, as it will make your bubbles even better.
-When you’re ready, dip your bubble wand into the mixture and start blowing bubbles!

-----------------
_Note: The solutions with a ✔️ don't have 'weird ingredients'._
