### ISSUE TITLE
Bug: Find and insert electrical socket protectors 🔌⚡️

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#63]
A few of the electrical sockets in the (current) “play room” are currently not protected:

![IMG_4120](https://github.com/bmhco/shared/assets/194400/6f257651-2aaf-4781-aeca-c4b1781692e5)

![IMG_4120](https://github.com/bmhco/shared/assets/194400/47aaae94-f6b6-4dfe-bfa9-7bf7c0155dda)

this is not a _safety_ risk because all our sockets are safety sockets. I.e. touching them will not cause a shock. The only way for an infant to get a shock (which could be fatal!) would be if they insert something metallic into it …

but it’s the *perception* of risk we want to mitigate by putting protectors in the socket.

# Todo

+ [ ] locate the protectors that were removed.
+ [ ] put protectors in all sockets that are not in-use (I.e. don’t have something plugged into them)
+ [ ] define a *system* for this so that we avoid any issues with *future* (visiting) children/pets.

@Stephanymtr hopefully you can help with the first two items on this list. Then @iteles can add a sentence to the handbook when she has some time. 👌

**Comment by Stephanymtr** [comment]
I went around the house and managed to find 4 outlet plug covers which is the amount you needed. All the outlets in the playroom are now protected including the one next to the baby play mat. 

![image](https://github.com/bmhco/shared/assets/91985721/1f08621f-5fb8-4c0c-94ff-d839d35d1098)![image](https://github.com/bmhco/shared/assets/91985721/4cf53da8-8c4a-48d5-a81a-2d4c43417c85)![image](https://github.com/bmhco/shared/assets/91985721/f3a31a7d-d730-4042-be7c-15dbc90d2940)![image](https://github.com/bmhco/shared/assets/91985721/d9111a64-b2f6-43ea-9b9c-959812817b87)

I shared the photos of the outlets that didn't have covers on to help you create a system. Winter is coming in a few months, and these might need to be taken off again so that the portable heaters can be used. 

During my search for these covers, I found 2 outlet plug removers. I put them in this basket that's on the table in the dining room. If there's better spot for it, please lmk where and I'll move it. Thanks!

![image](https://github.com/bmhco/shared/assets/91985721/8cecd8bb-b291-4ca3-ab20-2f7a432e6039)

**Comment by nelsonic** [comment]
Thanks @Stephanymtr ✅ 
Now we just need a few words on a "System" that we can share with `people` in the House for the future. 📝
