### ISSUE TITLE
LEGO (duplo) should *all* be available always

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#64]
Our son *loves* playing with LEGO (duplo)

![IMG_4195](https://github.com/bmhco/shared/assets/194400/8d4c93a9-1905-4bd8-9a24-4d87662660df)

and yet *most* of the pieces are hidden from view in the Attic of all places! WHY?! 🤷‍♂️😢

why do we *waste* money on awesome learning materials and then hide them away where we cannot play with them?!?! 🤦‍♂️

**Comment by nelsonic** [comment]
We finished all the blocks in the box - which is incomplete - in _less_ than **5 minutes**

![IMG_4204](https://github.com/bmhco/shared/assets/194400/d5b97a7b-edfb-4a5c-85ce-87a9cf2d333b)
 
 and the tower we made is tiny:

![IMG_4207](https://github.com/bmhco/shared/assets/194400/b1268171-b991-4e8f-b219-8f68d6b1eb69)

If you’re not familiar with the how children play LEGO (duplo) at this age, the whole point is to build a BIG building; as big as possible, without it falling over. And then once you’ve used up all the blocks, knock it over and start again!

![IMG_4208](https://github.com/bmhco/shared/assets/194400/ad7021b0-23ad-4af2-ab83-2e1dedf3c525)

If there are fewer than 50 blocks the game doesn’t last very long… 🙃

**Comment by iteles** [comment]
Toy rotation is why we have toys stored away. 

Up until now we've had a set of construction toys (either blocks or Lego or train tracks or Magnatiles) out at all times. But I totally agree we're now at the phase where we want to encourage big 'let's build' actions and focus in on his interests. 

@Stephanymtr - the task here is to pull together ALL our duplo. 

We will be using duplo for a while still before moving onto standard legos because of 👶 

## Tasks
+ [ ] Get the two tubs of standard size Lego that are in the piano room in the basement and store in the attic to keep 👶 safe
+ [ ] Pull out all our Lego duplo
+ [ ] Take photos of ANY sets that don't have photos/pieces maps (like the fire truck set)
+ [ ] Put animals and characters into a smaller box to keep separate (easily findable)
+ [ ] Decide what size box we need for legos and source it based on what we have (shouldn't be a tight fit as I WILL buy more)
+ [ ] Make a sign for the box with Lego duplo logo in big and 'Para ficar neste andar da casa e não sair à rua' underneath
+ [ ] Print signs
+ [ ] Plasticise sign and stick to box

**Comment by nelsonic** [comment]
Toy ("Learning Materials") Rotation is why we keep _wasting_ money and _time_ on things he plays with _once_. ⏳ 💸 🔥 
We don't have a Materials Catalog e.g: in an issue or markdown file 📝 
so the _only_ person who knows what we have is the most exhausted and memory-compromised person ... 🧠 

All `Duplo` _must_ be available at all times. Hiding it away is a crime.

**Comment by Stephanymtr** [comment]
I went to the basement and collected the only Lego container that I saw in the piano room. I took it upstairs to the attic and stored it on the Lego shelf. 

![image](https://github.com/bmhco/shared/assets/91985721/8b33ee62-6bd1-447f-9409-c32f91d4e0de)Photo of Lego on the shelf 

![image](https://github.com/bmhco/shared/assets/91985721/deebc85c-e47f-47cb-98be-b01ffd758ca0)

I didn’t find the “two tubs of standard size Lego” that mentioned above. Do you have a photo of those tubes ? 

I went to attic and collected the rest of the Lego duplo boxes and a few Lego vehicles that were stored upstairs too. This is ALL the Lego Duplo I managed to find and collect in one spot. 

![image](https://github.com/bmhco/shared/assets/91985721/ba301dd3-b31c-4859-833a-7b30c1843324)

Regarding the fire truck set you mentioned above, I’m assuming you were talking about the legos that were inside a bowl in the kitchen. I pulled them out and took a photos of everything that was inside that bowl.

![image](https://github.com/bmhco/shared/assets/91985721/3f596cbf-7484-47a4-bc82-cffd719b449f)Photos of Lego from inside bowl 

![image](https://github.com/bmhco/shared/assets/91985721/6680f41e-b059-4eb4-bcac-0ee83b6c2c88)

I transferred all the legos to this transparent container. Sadly, if you want to put a lid on this box, that red flat base won’t fit in it. So it will have to be stored outside the box.

![image](https://github.com/bmhco/shared/assets/91985721/8c0da18b-be9c-41f8-a32e-0054d9431e75)

Here are all the characters, animals, a few small small Lego pieces, and a random toy that doesn’t look like it belongs here (which I moved it back to the attic). 

![image](https://github.com/bmhco/shared/assets/91985721/37b16932-6612-4f7f-a378-297b3778c249)

Here is the small box I found for the small bits 

![image](https://github.com/bmhco/shared/assets/91985721/55839144-1304-498e-8cdf-dd934aa75090)

![image](https://github.com/bmhco/shared/assets/91985721/f3617264-d771-4961-9f56-c009d21edd16)

I took all the empty Lego boxes/containers back upstairs to be stored in the attic. 

![image](https://github.com/bmhco/shared/assets/91985721/e1862928-8a73-4cf0-b748-131d2e346661)


I took many trips from downstairs to the attic and back, but it's done ✅ I know I still need to print the, laminate and tape the label on the box.

![image](https://github.com/bmhco/shared/assets/91985721/bcafcc1a-2b34-4adb-ae4c-998a927ec608)

**Comment by Stephanymtr** [comment]
Label has been printed and laminated. Done ✅ ![image](https://github.com/bmhco/shared/assets/91985721/0ef480be-fec6-4760-8d0c-41676ad80728)

**Comment by iteles** [comment]
This looks great, thanks @Stephanymtr.

I would be tempted to have the fire engine bits in one pouch, just because it's a cool thing to have together and it'll be a real pain to go through the box to find everything.

What do you think @nelsonic ?

**Comment by Stephanymtr** [comment]
You're welcome! @iteles 
When you say the fire engine bits, are you talking about the extra accessories like the fire, rescue tool and the little fire man or the fire engine and its little accessories like the ladder, hose etc ?

**Comment by nelsonic** [comment]
@iteles we need to buy 10x more than what we have so we can build a *serious* village/castle. 

We could easily more than double our piece count by getting a set with a few hundred pieces, e.g: https://www.olx.pt/d/anuncio/lego-duplo-thomas-and-friends-IDHE9bl.html
![IMG_8765](https://github.com/bmhco/shared/assets/194400/dbda8a3c-0c13-4af7-87b4-4f6d14767169)

**Comment by iteles** [comment]
@nelsonic This is a cool set if you want the train tracks in Lego portion of it. If not and what you actually want is Lego building blocks (which I think are cooler for creativity), then there are lots of 100 piece sets you can get on Vinted for a better price (admittedly more air miles):

https://www.vinted.pt/items/3399121536-lot-duplo
![image](https://github.com/bmhco/shared/assets/4185328/a581f144-4e32-4951-8efc-659932698d70)

https://www.vinted.pt/items/3400348957-1-caisse-lego-duplo
![image](https://github.com/bmhco/shared/assets/4185328/49f8e59f-6a6e-45cd-adae-ef67cc648852)

https://www.vinted.pt/items/3400168678-duplo-bouwblokken
![image](https://github.com/bmhco/shared/assets/4185328/d02699ed-47e9-4bec-b588-ff6ee06c61f4)

https://www.vinted.pt/items/3398208721-lego-duplo
![image](https://github.com/bmhco/shared/assets/4185328/bd1348bd-5f13-4aae-b73a-ade74f3037a6)

**Comment by nelsonic** [comment]
As noted above, I’m keen on having a “wow” collection of Lego/Duplo. So please use my Monzo card and just buy anything that looks decent. I’m keen to have a Lego _area_ of the house either in this house or the next. 🧱

**Comment by nelsonic** [comment]
Didn't get a _reply_ on this request to buy more Duplo 11 months ago, so I'm buying it myself. 
Watching the market on Vinted, which appears to be where sellers across Europe sell-off their unwanted collections. 

Recently made a ("lowball") offer on a 400+ piece set:

![image](https://github.com/user-attachments/assets/b499c5d6-ad61-430e-a24a-47eeb8cb2f1f)

> Asking price: €50
> Paid: €45 including shipping

And another 200+ piece set with *many* animals:

![image](https://github.com/user-attachments/assets/41e44a2a-ae44-4276-948d-82d7be0bde4c)

> Asking price €42; 
> Paid: €38 incl postage. 


This will more than *double* our collection.
In the short term we can continue keeping it in large IKEA tub in the (indoor) "playroom".
But once our "secret garden" is finished, we will have a dedicated Lego/Duplo covered *outdoor* play area.

**Comment by nelsonic** [comment]
FYI: planning on making a section of the Top floor of the Secret Garden (once it's finished) into our Lego Area. ref: https://github.com/bmhco/shared/issues/98
