### ISSUE TITLE
First Aid Cabinet ⛑️ 🩹 🤒 

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#70]
A few weeks ago, the _potentially_ hazardous chemicals (e.g: betadine & 97% alcohol) were removed from the drawer in the middle floor bathroom and put “upstairs” (_somewhere I don’t know where …_).

A few days ago our son scratched his knee when he fell on asphalt and I couldn’t find any liquid to disinfect the wound; it was very frustrating to have a crying child and no first aid liquid on hand. 😢

# Todo

+ [x] list all the items we *need* to have in a first aid cabinet. 

+ [x] agree on location/placement and size required for our First Aid cabinet.

+ [x] research available cabinets we can *buy*. If there is something _not_ ugly. We can buy it.  If not, I’m happy to *make* something in the workshop as it will be custom to the space available and look *muuuch* better than something plastic. 💭

+ [x] buy our build the cabinet!

+ [x] mount it to the wall (in the agreed place)

+ [ ] Populate the cabinet with the required supplies

I quite like the look of this wooden cabinet:
https://www.discountschoolsupply.com/school-supplies/health-safety/cleaning-sanitation/lockable-first-aid-cabinet/p/34325

![IMG_8416](https://github.com/bmhco/shared/assets/194400/4b8f7e9a-f49d-4fd2-bfef-348ef93c982f)

but am *definitely not* paying $600 for one!! 🤯💸

**Comment by iteles** [comment]
Wowza. $600.

Would a child lock on the existing bathroom drawers not work?
If I'm in pain or in a hurry, faffing with keys that cannot be left in the lock is not ideal, but grabbing a magnet from an out of the way place and opening a drawer is doable.

If we want a cabinet, we should check how much space we have but I think this is a good option:
https://amzn.to/3QWuaoP
<img width="1415" alt="image" src="https://github.com/bmhco/shared/assets/4185328/2699dab1-3b1b-4542-b6a0-3e3b95b8a231">

Will make a list of what we need asap.

**Comment by nelsonic** [comment]
The magnetic child locks are horrible for everyone except the person that _installed_ them and knows the "secret". 
The First Aid Cabinet needs to be at _adult_ eye height and _dedicated_ to the single purpose of first aid.
We can leave the key in the lock and the spare on a string above so that even if someone removes one they won't lose the other. 
The drawers under the sink can still be used for non-toxic chemicals like hand soap refills, sterile gloves and TP.

**Comment by nelsonic** [comment]
This Amazon cabinet you have shared is €50 on the `ES` store:

<img width="1464" alt="amazon-es-firstaid-cabinet" src="https://github.com/bmhco/shared/assets/194400/eef84e89-3480-4d08-bd10-be540b828701">

It's also _tiny_ ... it's basically the size of an **`A4`** sheet of paper and the depth of single bottle of something. 

For reference, this one from Leroy (marketplace) is the same dimensions as the AMZN one you shared:
https://www.leroymerlin.pt/produtos/armario-de-primeiros-socorros-gabinete-de-medicamentos-de-parede-de-metal-216-x-80-x-321-mm-83789300.html **`€33.61`** with _free_ delivery ...
<img width="1396" alt="image" src="https://github.com/bmhco/shared/assets/194400/c0db26af-3131-43be-a585-1ea3d1e5d87e">

You can see how _tiny_ it is with reference to the standard size bottles inside ... 📏 

<img width="1131" alt="image" src="https://github.com/bmhco/shared/assets/194400/0215decb-12c6-4d70-bbfe-03112dd0d261">

> **Note**: This is actually _more_ than "enough" in a _minimalist_ first aid cabinet. 

I think I'd _prefer_ to have something bigger ... because we _already_ have quite a lot of items to store in it. 💭 
If we store all the different kinds of plasters, gauses and liquids we _already_ have we immediately exceed this size.

Perhaps we should take a step back and figure out _everything_ that makes sense to store in a First Aid Cabinet ...

Meanwhile there are decent options at Leroy for cheaper than the AMZN ES price:
https://www.leroymerlin.pt/search?q=primeiros+socorros

e.g: https://www.leroymerlin.pt/produtos/casas-de-banho/moveis-de-casa-de-banho/armarios-de-casa-de-banho/armarios-de-casa-de-banho-para-medicamentos/armario-farmacia-kleankin-30x14x46-cm-branco-87912371.html
<img width="1461" alt="image" src="https://github.com/bmhco/shared/assets/194400/30dddcd2-cf04-40fe-8ee1-c28b11e66b05">

<img width="1131" alt="image" src="https://github.com/bmhco/shared/assets/194400/6dab1573-2919-4984-a6d5-a7bbf9cba606">

Yes, this is more expensive but it's more than _double_ the volume and means we can store _all_ of the First Aid `items` we already have. 

<hr />

searched on Quirumed https://www.quirumed.com/pt/#/dfclassic/query=primeiros%20socorros which we have bought from in the past but their similar sized cabinet was **`€98`**: https://www.quirumed.com/pt/caixa-de-primeiros-socorros-a-5-com-chave.html
<img width="1114" alt="image" src="https://github.com/bmhco/shared/assets/194400/f9227f36-3dd4-4ce0-887a-3e6dd9406dfc">
The cheaper options were smaller/worse. So don't bother looking there.

Also searched KuantoKusta product price comparison site: https://www.kuantokusta.pt/search?q=primeiros+socorros+movel 
<img width="1184" alt="image" src="https://github.com/bmhco/shared/assets/194400/18bd56c3-0d1a-44c8-a2bb-4b4319712bcd">


https://www.aosom.pt/item/homcom-armario-de-medicinas-botiquin-gabinete-de-primero-auxilios-acero-inox-3-estantes-caja-colgante-de-pared-con-cerradura-25x12x48cm~02-0546.html
<img width="1246" alt="image" src="https://github.com/bmhco/shared/assets/194400/de2295a4-0587-416d-b76a-8632dcc8e485">

Dunno if the `Inox` look is what we want ... But I like the translucent front. Would prefer _transparent_. 
But opaque is easier to keep clean. So happy to go with whatever you decide. Just be aware of the size. 👌

**Comment by Stephanymtr** [comment]
A well-stocked first aid cabinet is essential for addressing minor injuries and medical emergencies that may occur at home. Here is a list of supplies and medicines:

**Basic Supplies:**

- Adhesive Bandages: Various sizes and shapes to cover cuts and wounds.
- Sterile Gauze Pads: Used for cleaning and covering wounds.
- Adhesive Tape: Secure gauze, bandages, and dressings in place.
- Antiseptic Wipes or Solution: To clean wounds and prevent infection.
- Cotton Balls and Swabs: For cleaning and applying ointments.
- Scissors: For cutting tape, gauze, and clothing if needed.
- Tweezers: To remove splinters or foreign objects.
- Thermometer: Digital thermometers are convenient and accurate.
- Disposable Gloves: For infection control and protection.
- CPR Face Shield or Mask: Important for performing CPR safely.
- Instant Cold Packs: To reduce swelling and pain.
- Hot Water Bottle: Useful for applying heat to sore muscles.
- Elastic Bandage (e.g., Ace bandage): For supporting sprains and strains.
- First Aid Manual: Provides guidance on basic first aid procedures.
- Safety Pins: Useful for securing bandages or clothing.

**Medications:**

- Pain Relievers: Over-the-counter pain relievers like acetaminophen (Tylenol) and ibuprofen (Advil or Motrin).
- Antihistamines: For allergies and insect bites (e.g., Benadryl).
- Antacids: For digestive issues and heartburn.
- Cough and Cold Medicine: Depending on family needs.
- Anti-diarrheal Medication: For gastrointestinal discomfort
- Laxatives: In case of constipation.
- Oral Rehydration Salts: Important for treating dehydration.
- Eye Drops: For minor eye irritations or allergies.
- Topical Hydrocortisone Cream: To relieve itching and skin irritations.
- Calamine Lotion: For soothing rashes and itching.

**Additional Items:**
Baby supplies like baby aspirin, diaper rash cream, and baby-specific bandages.

**Comment by iteles** [comment]
I checked Leroy Merlin and the options above are unavailable throughout the country and I didn't see any others I liked. 

This might be an option:

https://www.aosom.pt/item/kleankin-armario-farmacia-de-parede-armario-de-medicamentos-de-aco-com-3-niveis-porta-magnetica-30x12x60-cm-branco~1IMHR62QG6001.html
![image](https://github.com/bmhco/shared/assets/4185328/d6ddb8b9-5c20-4f1d-91ba-f61ef729e6ec)

**Comment by nelsonic** [comment]
@iteles please include the price when sharing an item:
https://www.aosom.pt/item/kleankin-armario-farmacia-de-parede-armario-de-medicamentos-de-aco-com-3-niveis-porta-magnetica-30x12x60-cm-branco~1IMHR62QG6001.html

<img width="1711" alt="image" src="https://github.com/bmhco/shared/assets/194400/36ed1bd7-a03f-4bc0-b640-10261584696c">

`€49.99` seems reasonable. `12cm` deep should work.
Should we order this on `#BlackFriday` `€42,49` ...

**Comment by iteles** [comment]
@nelsonic On closer inspection, the model above doesn't have a key, which I think we do need (even if we keep it ontop of the cabinet, the important part is out of the hands of children).

There is this model which I prefer because it has the green cross (but we can buy a decal for that):
https://www.aosom.pt/item/kleankin-armario-farmacia-de-parede-em-aco-com-3-prateleiras-de-armazenamento-e-2-chaves-para-casa-de-banho-30x14x46-cm~1DRT4B6KHLG00.html
<img width="1248" alt="image" src="https://github.com/bmhco/shared/assets/4185328/a783106e-262b-4263-94ff-d3ba2cb6c074">

Or this one which is a bit bigger:
https://www.aosom.pt/item/kleankin-armario-farmacia-de-parede-com-3-prateleiras-de-armazenamento-e-fechadura-com-2-chaves-40x18x60cm-branco~1D0MUFVE03001.html
<img width="1241" alt="image" src="https://github.com/bmhco/shared/assets/4185328/f816cf0d-dfa3-4afb-b34b-d7a5267ddba5">

What do you think?

**Comment by nelsonic** [comment]
@iteles while I _prefer_ the **`18cm`** deep cabinet (the second one you've shared). 

I was thinking of placing the First Aid Cabinet above the Dyson Hand Drier which is **`10cm`** deep:
<img width="614" alt="image" src="https://github.com/bmhco/shared/assets/194400/42fa9eb1-abca-4b3e-86d3-0229d11d63a2">

If instead we place the cabinet on the wall adjacent to the W/C then the depth is not an issue:

![image](https://github.com/bmhco/shared/assets/194400/00d01727-210b-4b5f-9317-2ce6e98f66f8)

I'd go with the larger one even though it means we're likely to accumulate more stuff in there ... 💭 

As for the green decal, we can easily buy one at a later date. 👌

**Comment by iteles** [comment]
The only reason I might not be keen on placing on the wall next to the w/c is because I'm not sure we can change the side to which the door of the cabinet opens.
Can you tell from the images/listings if we can?

If we open a door into the mirror with a key still in it, the likelihood is that if this is done with any urgency it could crack the mirror, which would be a HUGE pain and would have be placing it above the hand dryer every day of the week...

**Comment by nelsonic** [comment]
A quick glance at the mounting holes on the rear of the cabinet and the design indicates that you can just flip it 180* and have the door on either side. 

But also, the hinge is totally removable: 

<img width="336" alt="image" src="https://github.com/bmhco/shared/assets/194400/20de175a-0da2-402f-870a-bf99a9710156">

So we could easily mount it on the other.

_However_ ... I just checked Amazon ES and there is a similar sized cabinet that I _prefer_:
https://www.amazon.es/-/pt/dp/B00P6DW0FE
<img width="1088" alt="image" src="https://github.com/bmhco/shared/assets/194400/eda68b42-573f-4ffa-b9a2-177827cbb621">

It's stainless steel (inox) and has a frosted glass door and _cheaper_ (though smaller)

![image](https://github.com/bmhco/shared/assets/194400/d30346dc-89b0-4be5-892e-0af5fcab6356)


https://www.amazon.es/-/pt/dp/B007MXSWMQ/
<img width="951" alt="image" src="https://github.com/bmhco/shared/assets/194400/a988f9b4-2bc8-4709-b4d8-0a8205e38aca">

I'd actually be willing to spend a bit more to have an _attractive_ cabinet: 
https://www.amazon.es/-/pt/dp/B08HJ5MZCG
<img width="1057" alt="image" src="https://github.com/bmhco/shared/assets/194400/a6998991-ec79-4eb2-ba3e-8ea4085d6e51">

Given that I have to _look_ at it every day ... 💭 

But ultimately this is a utilitarian thing. So go with whichever you feel meets our needs. 👌

**Comment by iteles** [comment]
If you think 50 x 30 x 18 cm is both big enough and won't stick out over the hand dryer by far too much (the AOSOM one I suggest above is 14cm deep), then get that one.

If not, let me know and I'll buy the AOSOM one now, which is €43,73 with the Black Friday 'sem IVA' promotion 👍 
https://www.aosom.pt/item/kleankin-armario-farmacia-de-parede-em-aco-com-3-prateleiras-de-armazenamento-e-2-chaves-para-casa-de-banho-30x14x46-cm~1DRT4B6KHLG00.html?recv=eyJwYWdldHlwZSI6ImNydCJ9

**Comment by nelsonic** [comment]
@iteles `50cm x 30cm x 18cm` is _more_ than big enough for the items we need to store in it ...
I might not be _aware_ of everything that _you_ want to store in the cabinet ...
But from my experience of previous workplaces, the med cabinet tends to be quite small ...

**Comment by iteles** [comment]
No I'm totally happy with the size of the Amazon one, just didn't want the overhang to be too big.

Awesome, added the Amazon one to the cart 👍

**Comment by nelsonic** [comment]
Order placed. ✅

**Comment by nelsonic** [comment]
Arrived:

![IMG_7776](https://github.com/bmhco/shared/assets/194400/0c4093ff-d232-4299-bdbe-5392d23fdc23)

@iteles if you have 2 mins today to agree on the placement I can install/wall-mount it in 10mins. 👌

**Comment by nelsonic** [comment]
*finally* got agreement from Inês on the placement.
Measured the height and perfect distance from the mirror - so that the cabinet door _cannot_ bump into the mirror:

![IMG_6479](https://github.com/bmhco/shared/assets/194400/b711bd4e-1deb-4380-9522-b53dafdba9a8)

drilled the holes and mounted it to the wall:

![IMG_6480](https://github.com/bmhco/shared/assets/194400/f3b4162b-e055-4cda-bbe5-bfefbceabd1d)
![IMG_6481](https://github.com/bmhco/shared/assets/194400/d4c30bb0-0049-4338-9696-1832c729a044)

so the *easy* (handyman) part is **done**. 
now we just have to populate the cabinet. 
assigning to @iteles for adding items to cabinet.

**Comment by nelsonic** [comment]
Closing as the cabinet is installed and has been used a few times. ✅
