### ISSUE TITLE
[EPIC] Chore: `@home` Physical Risk Assessment

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#8]
We need to capture a video "walkthrough" of **all areas** that will be accessible to visiting children.
The video will be used by us _internally_. 

+ [ ]  **Doorbell** https://github.com/dwyl/home/issues/201 needs to be _finished_ as it is the literal **_first_ impression** people have when they visit. 
    It's not a safety issue from a risk-assessment perspective ... but it is lame to not have a doorbell and parents 
+ [ ]  **Front _Gate_** - is it safe _or_ can children get their fingers stuck? 
    Do we need a way to protect the latch from _anyone_ opening it? 
+ [ ] **Wires** - None of the wires outside are "live" but they are unsightly. 
    @iteles Can we get the Electricians over ASAP to get the external lighting finished and all wires/holes tidied? 
+ [ ]  **Front _Garden_** - inspect the garden and remove any loose items that could cause injury. (e.g. stones, pots, etc)
+ [ ] **Steps** are slippery when wet: https://github.com/dwyl/home/issues/212 is this risk _tolerable_?
+ [ ] **Hand Rail Gaps** -  on the south side of the hand rail, the gap is large enough that a child can get through. 
    Do we need to think of a way to close the gap?
+ [ ] Entrance ...

To be continued. ⌛

**Comment by Stephanymtr** [comment]
Hi @nelsonic, is there anything you think I could do to get this started ? I might be going over to the house this week. Perhaps I could take some before photos and videos of the outside and inside (main floor).

**Comment by nelsonic** [comment]
@Stephanymtr indeed. That's why I opened the issue to capture our _rough_ requirements. 📝 
Once you have done a basic tidy of the library, entrance, under-stairs and kitchen please LMK. 🙏

**Comment by Stephanymtr** [comment]
@nelsonic Alright, sounds good. I will add these to my to do list for the upcoming days.

**Comment by nelsonic** [comment]
Grip tape applied to exterior [granite] stairs to mitigate slips: https://github.com/dwyl/home/issues/212#issuecomment-1422337141 ✅

**Comment by Stephanymtr** [comment]
I haven't made much progress with the tidying up part of the main floor. However, given I walked around the garden in the morning, I had a few suggestions/questions, but first I wanted to know which part of the external areas will be open for children to play. Currently:
-> There are some construction materials on the pathway leading to the back of the house. Are you planning to install a gate in that area or will the little ones have access to the back of the house? 
-> Regarding the front portion of the garden, there are some plants on the edge of the pool. They are very heavy, so I can't imagine them being a risk, but I still wanted to mention it here in case you feel we need to brainstorm another location for them.
-> There's also some construction materials stored under the stairs. Given a gate was recently installed, will the kiddos have access to the sandpit / football pitch?

**Comment by nelsonic** [comment]
@Stephanymtr thanks for the update. 👍 
Tidying inside is very much dependent on availability from @iteles 📦 

Outside, children will be allowed to play freely in the "_front_" (north-west) garden.
The green gate was installed so that we can proceed with the construction project in the south-east garden ("hole").

Plants: #24 ✅ 

The construction materials under the stairs need to be moved. 
Ideally these will be taken to Landim early next week along with other materials.

As for access to the "football pitch" and sandpit. For the foreseeable future, yes, access is maintained.
Once the construction starts [TBD] the football area will be closed for a few weeks. ⏳
