### ISSUE TITLE
Feat: Register Your Interest Form

### ISSUE THREAD

**Issue by nelsonic** [bmhco/shared#9]
I order to capture + gauge interest/demand in the **`Playgroup`**, ❓ 
we need to create a form that stores data. 🔒 
From what we've seen, it _appears_ to be the "norm" to use Google Forms. 📝 
Luckily we have quite a lot of experience with this. 👌 

# Todo

+ [ ] Decide what fields we need to capture, e.g:
  + [ ] Parent / Guardian's Name
  + [ ] Email address
  + [ ] Mobile Phone Number (optional)
  + [ ] Age of child, e.g: **`22 months`** 
  + [ ] Level toilet independence: 
    1. Still uses diapers 100% of the time.
    2. Only uses diapers to sleep at night. Can use the toilet with help during the day.
    3. Only uses diapers at night. Can use the toilet independently.
    4. Other levels? 💭 
 + [ ] Create the form using our shared [`gmail`](https://github.com/bmhco/private/issues/129#issuecomment-1341172402) account. 

# Open Questions

+ [ ] Do we want to have the form in multiple languages? 
  e.g: `EN` & `PT`? What about `ES`, `DE`, `FR`, etc...?  (what languages do we `expect` parents to use?)
  (_this isn't difficult to achieve, and the `data` would all be in the same spreadsheet_) 
Again, luckily, we have plenty of experience with this: 
https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server 
extensively documented how to use Google Forms in "advanced mode". 🤓 
+ [ ] Do we want to have a link on the website to a separate Google Form (easiest & least SPAM) 
  ***or*** do we want to embed the form in the website to **_minimise_ friction**?

What _other_ considerations we need to have?

**Comment by nelsonic** [comment]
We currently have: https://bragamontessori.com/coming-soon/

![image](https://user-images.githubusercontent.com/194400/206726190-5863268b-cae7-4508-9091-6788f82cf0a0.png)

This is a **good _starting_ point** but we need to have a ***process*** for handing the email addresses collected ... 🤷‍♀️ 
And maybe we can update the image to something a bit more appropriate. 💭

**Comment by nelsonic** [comment]
@iteles / @Stephanymtr any other useful info you want to collect in the form? 💭 

Do you want to create the form based on our **`2.9k ⭐`** tutorial? https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server ***or*** want me to build a draft and you do final tweaks? 🧑‍💻

**Comment by Stephanymtr** [comment]
Hi, I believe you've got great questions! 

Will these be questions we ask parents who are **interested in enrolling their child into the playgroup** OR just **general questions we ask parents who want to know more about the playgroup**?  

I will share a few more questions that came to mind. However, if they are just curious about what we do, we shouldn't scare them away with very specific questions.

- [ ] Has your child attended any sort of child care center in the past? _This will allow us to know if the little ones have had any social experiences before. It should also prepare us to help them adjust to their new environment. We might encounter really shy kids along the way. This question should also be helpful for us to have an idea of the parents’ history with other centers and if they generally have good relationships with their child care providers._ 
- [ ] Does your child have any allergies ? 
or/and 
- [ ] Tell me about your child’s medical needs. Are there any health issues we should know about? 

I believe the form should be in English and Portuguese, so that it doesn't create confusion. More/other languages are welcome.

**Comment by nelsonic** [comment]
@Stephanymtr we want to get feedback from people who are _interested/curious_ about sending their kids to a Montessori Play Group in Braga. That means we should make the form as easy to fill-in as possible and still have a "general inquiries" form that just sends us an email. 

Cool. Allergies and Medical info are good but worth remembering that if we store "medical info" we have to have an _extra_ layer of security for handling/storing the data. https://edps.europa.eu/data-protection/data-protection/reference-library/health-data-workplace_en i.e. we are better off _not_ collecting the data in certain cases.
But ... I _agree_ that we should be aware of it up-front so that we can make informed decisions.
So perhaps this can be an _optional_ field where we axsk parents for any medical conditions we should be aware of.

As for language, I'm down for `EN` and `PT` as a good starting point. We need an _easy_ way of language switching. ♻️

**Comment by Stephanymtr** [comment]
This all sounds great! ✔️ 

> Do you want to create the form based on our 2.9k ⭐ tutorial? https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server or want me to build a draft and you do final tweaks? 🧑‍💻

Was this question for me or @iteles ? I think a draft would be a great first step.
